Answer.create(:id => 1, :question_id => 1, :content => " 100 million", :correct => false)
Answer.create(:id => 2, :question_id => 1, :content => "50 million", :correct => false)
Answer.create(:id => 3, :question_id => 1, :content => "15 million", :correct => true)
Answer.create(:id => 4, :question_id => 1, :content => "25 million", :correct => false)
Answer.create(:id => 5, :question_id => 2, :content => "grinding poverty among all classes of society.", :correct => false)
Answer.create(:id => 6, :question_id => 2, :content => "government oppression", :correct => true)
Answer.create(:id => 7, :question_id => 2, :content => "the ideas of the philosophes", :correct => false)
Answer.create(:id => 8, :question_id => 2, :content => "the insensitivity of Marie Antionette", :correct => false)
Answer.create(:id => 9, :question_id => 3, :content => "defeat England through an economic war", :correct => false)
Answer.create(:id => 10, :question_id => 3, :content => " consolidate the separate states of Germany", :correct => false)
Answer.create(:id => 11, :question_id => 3, :content => "create a united Europe under the leadership of France", :correct => true)
Answer.create(:id => 12, :question_id => 3, :content => "punish Russia for his ill-fated invasion", :correct => false)
Answer.create(:id => 13, :question_id => 4, :content => "by imposing a universal currency based on the French franc", :correct => false)
Answer.create(:id => 14, :question_id => 4, :content => "by the brutal suppression of guerrilla resistance", :correct => false)
Answer.create(:id => 15, :question_id => 4, :content => "by abolishing feudalism and manorialism.", :correct => true)
Answer.create(:id => 16, :question_id => 4, :content => "by encouraging French as the universal language", :correct => false)
Answer.create(:id => 17, :question_id => 5, :content => "1802", :correct => false)
Answer.create(:id => 18, :question_id => 5, :content => "1800", :correct => false)
Answer.create(:id => 19, :question_id => 5, :content => "1812", :correct => true)
Answer.create(:id => 20, :question_id => 5, :content => "1815", :correct => false)
